[window]

opacity = 1.0

padding.x = 0
padding.y = 0
dynamic_padding = true

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

startup_mode = "Maximized"

[font]

normal.family = "FiraCode Nerd Font Mono"

size = 20
